#ifndef Pinmap_h
#define Pinmap_h

#if defined(ARDUINO_AM_AP3_SFE_BB_ARTEMIS_ATP)

#define DISPLAY_CS_PIN 
#define DISPLAY_SDI_PIN 
#define DISPLAY_SDO_PIN 
#define DISPLAY_SCK_PIN 
#define SX1509_SCL_PIN 
#define SX1509_SDA_PIN 
#define MCP23017_SDA_PIN 
#define MCP23017_SLC_PIN 
#define FEEDLINE_PUMP_PIN 
#define FEEDLINE_END_DRAIN_VALVE_PIN 
#define FEEDLINE_WATER_VALVE_PIN 
#define FEEDLINE_MANIFOLD_DRAIN_VALVE_PIN 
#define DETERGENT_1_VALVE_PIN 
#define DETERGENT_2_VALVE_PIN 
#define DETERGENT_3_VALVE_PIN 
#define DETERGENT_4_VALVE_PIN 
#define DETERGENT_1_FLOW_PIN 
#define DETERGENT_2_FLOW_PIN 
#define DETERGENT_3_FLOW_PIN 
#define DETERGENT_4_FLOW_PIN 
#define FEEDLINE_FLOW_PIN 
#define DETERGENT_1_LEVEL_PIN 
#define DETERGENT_2_LEVEL_PIN 
#define DETERGENT_3_LEVEL_PIN 
#define DETERGENT_4_LEVEL_PIN 

#endif

#endif
