#ifndef Pinmap_h
#define Pinmap_h

#if defined(ARDUINO_TEENSY41)

#define DISPLAY_CS 10
#define DISPLAY_SDI 11
#define DISPLAY_SDO 12
#define DISPLAY_SCK 13
#define SX1509_SDA 18
#define SX1509_SCL 19
#define MCP23017_SDA 18
#define MCP23017_SLC 19
#define FEEDLINE_PUMP 25
#define FEEDLINE_END_DRAIN_VALVE 26
#define FEEDLINE_WATER_VALVE 27
#define FEEDLINE_MANIFOLD_DRAIN_VALVE 28
#define DETERGENT_1_VALVE 29
#define DETERGENT_2_VALVE 30
#define DETERGENT_3_VALVE 31
#define DETERGENT_4_VALVE 32
#define DETERGENT_1_FLOW 33
#define DETERGENT_2_FLOW 34
#define DETERGENT_3_FLOW 35
#define DETERGENT_4_FLOW 36
#define FEEDLINE_FLOW 37
#define DETERGENT_1_LEVEL 38
#define DETERGENT_2_LEVEL 39
#define DETERGENT_3_LEVEL 40
#define DETERGENT_4_LEVEL 41

#elif defined(ARDUINO_AM_AP3_SFE_BB_ARTEMIS_ATP)

#define DISPLAY_CS_PIN 
#define DISPLAY_SDI_PIN 
#define DISPLAY_SDO_PIN 
#define DISPLAY_SCK_PIN 
#define SX1509_SCL_PIN 
#define SX1509_SDA_PIN 
#define MCP23017_SDA_PIN 
#define MCP23017_SLC_PIN 
#define FEEDLINE_PUMP_PIN 14
#define FEEDLINE_END_DRAIN_VALVE_PIN 8
#define FEEDLINE_WATER_VALVE_PIN 10
#define FEEDLINE_MANIFOLD_DRAIN_VALVE_PIN 26
#define DETERGENT_1_VALVE_PIN 45
#define DETERGENT_2_VALVE_PIN 2
#define DETERGENT_3_VALVE_PIN 1
#define DETERGENT_4_VALVE_PIN 0
#define DETERGENT_1_FLOW_PIN 16
#define DETERGENT_2_FLOW_PIN 31
#define DETERGENT_3_FLOW_PIN 17
#define DETERGENT_4_FLOW_PIN 41
#define FEEDLINE_FLOW_PIN 9
#define DETERGENT_1_LEVEL_PIN 29
#define DETERGENT_2_LEVEL_PIN 11
#define DETERGENT_3_LEVEL_PIN 34
#define DETERGENT_4_LEVEL_PIN 33

#endif

#endif
